# Generated by Django 4.2 on 2024-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_ipaddress_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, max_length=30),
            preserve_default=False,
        ),
    ]
